# Generated by Django 3.1.7 on 2021-03-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gameID', models.IntegerField()),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=25)),
                ('wage', models.DecimalField(decimal_places=2, max_digits=9)),
                ('value', models.IntegerField()),
                ('description', models.TextField(max_length=280)),
            ],
        ),
    ]
